name: Pytest CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: .
        run: |
          python -m venv venv
          source venv/bin/activate
          export PYTHONPATH=.
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask server in background
        working-directory: .
        run: |
          source venv/bin/activate
          export PYTHONPATH=.
          nohup python app.py > flask.log 2>&1 &
          sleep 5

      - name: Run pytest tests
        working-directory: .
        run: |
          source venv/bin/activate
          export PYTHONPATH=.
          python tasks.py

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: report.html
          path: .
          retention-days: 3

      - name: Show Flask server logs
        if: always()
        working-directory: .
        run: cat flask.log